### ISSUE TITLE
fix staticfiles

### ISSUE THREAD

**Issue by komuw** [komuw/django-api-lambda#4]
when the following is set;

```bash
"proxy": {
        "command": "python app.py collectstatic --no-color --noinput; python app.py runserver 0.0.0.0:$PORT",
        "timeout": 25,
        "listen_timeout": 25
    },
```

we get the following error:
```bash
11:27:55am ERRO Traceback (most recent call last):
  File "app.py", line 26, in <module>
    execute_from_command_line(sys.argv)
  File "/var/task/.pypath/django/core/management/__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "/var/task/.pypath/django/core/management/__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/var/task/.pypath/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/var/task/.pypath/django/core/management/base.py", line 330, in execute
    output = self.handle(*args, **options)
  File "/var/task/.pypath/django/contrib/staticfiles/management/commands/collectstatic.py", line 199, in handle
    collected = self.collect()
  File "/var/task/.pypath/django/contrib/staticfiles/management/commands/collectstatic.py", line 124, in collect
    handler(path, prefixed_path, storage)
  File "/var/task/.pypath/django/contrib/staticfiles/management/commands/collectstatic.py", line 354, in copy_file
    if not self.delete_file(path, prefixed_path, source_storage):
  File "/var/task/.pypath/django/contrib/staticfiles/management/commands/collectstatic.py", line 304, in delete_file
    self.storage.delete(prefixed_path)
  File "/var/task/.pypath/django/core/files/storage.py", line 386, in delete
    os.remove(name)
    stage: staging
    version: 26

  11:27:55am ERRO OSError: [Errno 30] Read-only file system: '/var/task/static/admin/img/search.svg'
```

this is coz, the staticfiles mgmnt command is trying to write/delete files in/from `'/var/task/static/` which is a readonly filesystem. 

We need to figure out which paths in lambda are writeable and set staticfiles to go there.

**Comment by komuw** [comment]
seems like you can write to `/tmp` which has a limit of 512 MB

https://docs.aws.amazon.com/lambda/latest/dg/limits.html

**Comment by komuw** [comment]
Instead of compiling static files on every single request; `"command": "python app.py collectstatic --no-color --noinput; python app.py runserver 0.0.0.0:$PORT"` 
we would rather not gitignore static files and they will be shipped to lambda as part of the app.

**Comment by komuw** [comment]
we'll ignore staticfile handling for now.
